### ISSUE TITLE
Mensaje incompleto - Chrome android

### ISSUE THREAD

**Issue by bolderoctopus** [AustelBBS/chatserver#1]
Cuando te conectas a la cosa desde la aplicación de Chrome en Android, el mensaje que envías es recibido por los demás sin la primer letra.
Por ejemplo:
Envío "Hola"
Los demás reciben "ola".

**Comment by AustelBBS** [comment]
Es porque el diccionario solo cubre el alfabeto en minusculas, voy a arreglar eso en una actualizacion posterior. Si mandas la palabra en minusculas si agarra bien.

**Comment by bolderoctopus** [comment]
Cierto, no sale ninguna mayúscula

**Comment by AustelBBS** [comment]
Arreglado por bolderoctopus.
